Yii框架课程资料/yiiweb/blog/protected/modules/admin/controllers/ArticleController.php
<?php
/**
 * 文章管理控制器
 */
class ArticleController extends Controller{

	public function filters(){
		return array(
				'accessControl',
			);
	}

	public function accessRules(){
		return array(
			//更加具体化
			// array(
			// 	'deny',
			// 	'actions'=>array('del','add'),
			// 	'users'	=> array('admin')
			// 	),

			array(
				'allow',
				'actions'=>array('index', 'del','add'),
				'users'	=> array('@')
				),
			array(
				'deny',
				'users' => array('*')
				),


			);
	}


	/**
	 * 查看文章
	 */
	public function actionIndex(){
		$cri = new CDbCriteria();
		$articleModel = Article::model();
		$total = $articleModel->count($cri);

		$pager = new CPagination($total);
		$pager->pageSize = 3;
		$pager->applyLimit($cri);

		$articleInfo = $articleModel->findAll($cri);

		$data = array(
			'articleInfo'	=> $articleInfo,
			'pages'			=> $pager
			);

		$this->render('index', $data);
	}
	/**
	 * 添加文章
	 */
	public function actionAdd(){
		// $articleModel->thumb;
		// echo Yii::app()->BasePath;die;
		$articleModel = new Article();
		$category = Category::model();

		$categoryInfo = $category->findAllBySql("SELECT cid,cname FROM {{category}}");
		$cateArr = array();
		$cateArr[] = '请选择';
		foreach ($categoryInfo as $v) {
			$cateArr[$v->cid] = $v->cname;
		}

		$data = array(
			'articleModel'	=> $articleModel,
			'cateArr'		=> $cateArr
			);
		if(isset($_POST['Article'])){

			$articleModel->thumb = CUploadedFile::getInstance($articleModel, 'thumb');

			if($articleModel->thumb){
				$preRand = 'img_' . time() . mt_rand(0, 9999);
				$imgName = $preRand . '.' . $articleModel->thumb->extensionName;
				$articleModel->thumb->saveAs('uploads/' . $imgName);
				$articleModel->thumb = $imgName;

				//缩略图
				$path = dirname(Yii::app()->BasePath) . '/uploads/';

				$thumb = Yii::app()->thumb;
				$thumb->image = $path . $imgName;
				$thumb->width = 130;
				$thumb->height=95;
				$thumb->mode = 4;
				$thumb->directory = $path;
				$thumb->defaultName = $preRand;

				$thumb->createThumb();
				$thumb->save();
			}	


			$articleModel->attributes = $_POST['Article'];
			$articleModel->time = time();

			if($articleModel->save()){
				$this->redirect(array('index'));
			}
		}


		$this->render('add', $data);
	}


	public function actionDel($aid){
		$articleModel = Article::model();

		if($articleModel->deleteByPk($aid)){
			$this->redirect(array('index'));
		}
	}
}

Yii框架课程资料/yiiweb/blog/protected/modules/admin/controllers/CategoryController.php
<?php 
class CategoryController extends Controller{
	public function filters(){
		return array(
				'accessControl',
			);
	}

	public function accessRules(){
		return array(
			//更加具体化
			// array(
			// 	'allow',
			// 	'actions'=>array('del','add'),
			// 	'users'	=> array('admin')
			// 	),

			array(
				'allow',
				'actions'=>array('index', 'del','add', 'edit'),
				'users'	=> array('@')
				),
			array(
				'deny',
				'users' => array('*')
				),


			);
	}

	/**
	 * 查看栏目
	 */
	public function actionIndex(){
		$categoryModel = Category::model();
		$sql = "SELECT cid,cname FROM {{category}}";
		$categoryInfo = $categoryModel->findAllBySql($sql);

		$this->render('index', array('categoryInfo'=>$categoryInfo));
	}

	/**
	 * 添加栏目
	 */
	public function actionAdd(){
		$categoryModel = new Category();

		if(isset($_POST['Category'])){

			$categoryModel->attributes = $_POST['Category'];

			if($categoryModel->save()){
				$this->redirect(array('index'));
			}

		}
		// p($_POST);
		$this->render('add', array('categoryModel'=>$categoryModel));
	}



	/**
	 * 编辑栏目
	 */
	public function actionEdit($cid){
		$categoryModel = Category::model();
		$categoryInfo = $categoryModel->findByPk($cid);
		
		// p($_POST);
		if(isset($_POST['Category'])){
			$categoryInfo->attributes = $_POST['Category'];
			if($categoryInfo->save()){
				$this->redirect(array('index'));
			}
		}

		$this->render('edit', array('categoryModel'=>$categoryInfo));
	}


	/**
	 * 删除栏目
	 */
	public function actionDel($cid){
		$articleModel = Article::model();

		$sql = "SELECT aid FROM {{article}} WHERE cid=$cid";
		$articleInfo = $articleModel->findBysql($sql);

		if(is_object($articleInfo)){
			Yii::app()->user->setFlash('hasArt', '栏目下面有文章，请先删除文章');
			$this->redirect(array('index'));
			
		}else {
			if(Category::model()->deleteByPk($cid)){
				$this->redirect(array('index'));
			}
		}



	}


}

Yii框架课程资料/yiiweb/blog/protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends Controller
{

	public function filters(){
		return array(
				'accessControl',
			);
	}

	public function accessRules(){
		return array(
			//更加具体化
			// array(
			// 	'allow',
			// 	'actions'=>array('del','add'),
			// 	'users'	=> array('admin')
			// 	),

			array(
				'allow',
				'actions'=>array('index', 'copy'),
				'users'	=> array('@')
				),
			array(
				'deny',
				'users' => array('*')
				),


			);
	}
	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCopy(){
		$this->render('copy');
	}
}

Yii框架课程资料/yiiweb/blog/protected/modules/admin/controllers/LoginController.php
<?php
/**
 * 后台登陆控制器
 */
class LoginController extends Controller{
	/**
	 * 后台登陆模板
	 */
	public function actionIndex(){
		
		// p($userInfo->password);die;
		
		// var_dump(Yii::app()->db);
		$loginForm = new LoginForm();
		if(isset($_POST['LoginForm'])){
			$loginForm->attributes = $_POST['LoginForm'];

			if($loginForm->validate() && $loginForm->login()){
				Yii::app()->session['logintime'] = time();
				$this->redirect(array('default/index'));
			}
		}
		// p($_POST);die;
		

		$this->render('index',array('loginForm'=>$loginForm));
	}

	public function actions(){
		return array(
			'captcha'	=> array(
					'class'	=> 'system.web.widgets.captcha.CCaptchaAction',
					'height' => 25,
					'width'	 => 80,
					'minLength'=> 4,
					'maxLength'=> 4

				),

			);
	}

	public function actionOut(){
		Yii::app()->user->logout();
		$this->redirect(array('index'));
	}



}

Yii框架课程资料/yiiweb/blog/protected/modules/admin/controllers/UserController.php
<?php
/**
 * 后台用户管理控制器
 */
class UserController extends Controller{
	public function filters(){
		return array(
				'accessControl',
			);
	}

	public function accessRules(){
		return array(
			//更加具体化
			// array(
			// 	'allow',
			// 	'actions'=>array('del','add'),
			// 	'users'	=> array('admin')
			// 	),

			array(
				'allow',
				'actions'=>array('passwd'),
				'users'	=> array('@')
				),
			array(
				'deny',
				'users' => array('*')
				),


			);
	}
	/**
	 * 修改密码
	 */
	public function actionPasswd(){
		$userModel = User::model();
		if(isset($_POST['User'])){

			$userInfo = $userModel->find('username=:name', array(':name'=>Yii::app()->user->name));

			$userModel->attributes = $_POST['User'];
			if($userModel->validate()){
				$password = md5($_POST['User']['password1']);

				if($userModel->updateByPk($userInfo->uid, array('password'=>$password))){
					Yii::app()->user->setFlash('success', '修改密码成功');
				}
			}
		}
		// p($_POST);
		$this->render('index', array('userModel'=>$userModel));
	}
}

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/Login/index.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/login.css" />
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/login.js"></script>
	<title></title>
</head>
<body>
	<div id="divBox">
		<?php $form = $this->beginWidget('CActiveForm') ?>
			<?php echo $form->textField($loginForm, 'username', array('id'=>'userName')) ?>
			<?php echo $form->passwordField($loginForm, 'password', array('id'=>'psd')) ?>
			<?php echo $form->textField($loginForm, 'captcha', array('id'=>'verify')) ?>
			<input type="submit" id="sub" value=""/>
			<!-- 验证码 -->
			<div class="captcha">
				<?php $this->widget('CCaptcha',array('showRefreshButton'=>false,'clickableImage'=>true,'imageOptions'=>array('alt'=>'点击换图','title'=>'点击换图','style'=>'cursor:pointer'))); ?>
			</div>
		<?php $this->endWidget() ?>
		<div class="four_bj">
			
			<p class="f_lt"></p>
			<p class="f_rt"></p>
			<p class="f_lb"></p>
			<p class="f_rb"></p>
		</div>
		<ul id="peo">
			<li class="error"><?php echo $form->error($loginForm,'username') ?></li>
		</ul>
		<ul id="psd">
			<li class="error"><?php echo $form->error($loginForm,'password') ?></li>
		</ul>
		<ul id="ver">
			<li class="error"><?php echo $form->error($loginForm,'captcha') ?></li>
		</ul>
	</div>
<!--[if IE 6]>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/iepng.js"></script>
    <script type="text/javascript">
        DD_belatedPNG.fix('form','background');
    </script>
<![endif]-->
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/article/add.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/public.css">
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/org/ueditor/ueditor.all.min.js"></script>
	<script type="text/javascript">
		window.UEDITOR_HOME_URL = "<?php echo Yii::app()->request->baseUrl ?>/assets/admin/org/ueditor/";
		window.onload = function(){
			window.UEDITOR_CONFIG.initialFrameWidth = 900;
			window.UEDITOR_CONFIG.initialFrameHeight = 600;
			UE.getEditor('content');
		}

	</script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/org/ueditor/ueditor.config.js"></script>
	<title>Document</title>
</head>
<body>
	
	<?php 
		$form = $this->beginWidget('CActiveForm', array('htmlOptions'=>array('enctype'=>'multipart/form-data')));
	 ?>
	<table class="table">
		<tr >
			<td class="th" colspan="10">发表文章</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'title') ?></td>
			<td>
				<?php echo $form->textField($articleModel, 'title', array('maxlength'=>20)) ?>
				<?php echo $form->error($articleModel, 'title') ?>
			</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'type') ?></td>
			<td>
				<?php 
					echo $form->radioButtonList(
						$articleModel,
						'type',
						array(0=>'普通',1=>'热门'),
						array('separator'=>'&nbsp')
						)
				 ?>
			
			</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'cid') ?></td>
			<td>
				<?php echo $form->dropDownList($articleModel,'cid', $cateArr) ?>
				<?php echo $form->error($articleModel, 'cid') ?>
			</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'thumb') ?></td>
			<td>
				<?php echo $form->fileField($articleModel, 'thumb') ?>
				<?php echo $form->error($articleModel, 'thumb') ?>
			</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'info') ?></td>
			<td>
				<?php echo $form->textArea($articleModel, 'info', array('cols'=>50,'rows'=>10,'maxlength'=>100)) ?>
				<?php echo $form->error($articleModel, 'info') ?>
			</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($articleModel, 'content') ?></td>
			<td>
		
				<?php echo $form->textArea($articleModel, 'content',array('id'=>'content')) ?>
				<?php echo $form->error($articleModel, 'content') ?>
			</td>
		</tr>
		<tr>
			<td colspan="10"><input type="submit" class="input_button" value="发布"/></td>
		</tr>
	</table>
	<?php $this->endWidget() ?>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/article/index.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/public.css">
	<title>Document</title>
</head>
<body>
	<table class="table">
		<tr>
			<td class="th" colspan="10">查看文章</td>
		</tr>

		<tr>
			<td>AID</td>
			<td>标题</td>
			<td>栏目</td>
			<td>发表时间</td>
			<td>操作</td>
		</tr>
		
		<?php foreach($articleInfo as $v): ?>
			<tr>
				<td><?php echo $v->aid ?></td>
				<td><?php echo $v->title ?></td>
				<td><?php echo $v['cate']->cname ?></td>
				<td><?php echo date('h:i:s', $v->time) ?></td>
				<td>
					[<a href="">编辑</a>]
					[<a href="<?php echo $this->createUrl('del', array('aid'=>$v->aid)) ?>">删除</a>]
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	<div class="page">
		<?php 
			$this->widget('CLinkPager', array(
				'header'	=>	'',
				'firstPageLabel'	=> '首页',
				'lastPageLabel'	=> '末页',
				'prevPageLabel'	=> '上一页',
				'nextPageLabel'	=> '下一页',
				'pages'			=> $pages,
				'maxButtonCount'=> 5,
				

				));
		 ?>
	</div>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/category/add.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/public.css">
	<title>Document</title>
	<style type="text/css">
		span{
			color: #f00;
		}
	</style>
</head>
<body>
	<?php $form = $this->beginWidget('CActiveForm',array(
		'enableClientValidation'=> true,
		'clientOptions' => array(
				'validateOnsubmit'	=> true
			),
	)) ?>
	<table class="table">
		<tr>
			<td class="th" colspan="10">添加栏目</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($categoryModel, 'cname') ?></td>
			<td>
				<?php echo $form->textField($categoryModel, 'cname') ?>
				<?php echo $form->error($categoryModel, 'cname') ?>
			</td>
		</tr>
		<tr>
			<td colspan="10"><input type="submit" value="添加" class="input_button"/></td>
		</tr>
	</table>
	<?php $this->endWidget() ?>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/category/edit.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/public.css">
	<title>Document</title>
	<style type="text/css">
		span{
			color: #f00;
		}
	</style>
</head>
<body>
	<?php $form = $this->beginWidget('CActiveForm',array(
		'enableClientValidation'=> true,
		'clientOptions' => array(
				'validateOnsubmit'	=> true
			),
	)) ?>
	<table class="table">
		<tr>
			<td class="th" colspan="10">修改栏目</td>
		</tr>
		<tr>
			<td><?php echo $form->labelEx($categoryModel, 'cname') ?></td>
			<td>
				<?php echo $form->textField($categoryModel, 'cname') ?>
				<?php echo $form->error($categoryModel, 'cname') ?>
			</td>
		</tr>
		<tr>
			<td colspan="10"><input type="submit" value="修改" class="input_button"/></td>
		</tr>
	</table>
	<?php $this->endWidget() ?>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/category/index.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/public.css">
	<title>Document</title>
</head>
<body>
	<?php 
		if(Yii::app()->user->hasFlash('hasArt')){
			echo Yii::app()->user->getFlash('hasArt');
		}
	 ?>
	<table class="table">
		<tr>
			<td class="th" colspan="10">查看栏目</td>
		</tr>
		<tr>
			<td>CID</td>
			<td>栏目名称</td>
			<td>操作</td>
		</tr>

		<?php foreach($categoryInfo as $v): ?>
			<tr>
				<td><?php echo $v->cid ?></td>
				<td><?php echo $v->cname ?></td>
				<td>
					[<a href="<?php echo $this->createUrl('edit', array('cid'=>$v->cid)) ?>">编辑</a>]
					[<a href="<?php echo $this->createUrl('del', array('cid'=>$v->cid)) ?>">删除</a>]
				</td>
			</tr>
		<?php endforeach ?>
	</table>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/default/copy.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title></title>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/admin.css" />
</head>
<body>
	<table class="table">
		<tr>
			<td colspan='2' class="th"><span class="span_people">&nbsp</span>欢迎光临管理后台</td>
		</tr>
		<tr>
			<td>用户名</td>
			<td><?php echo Yii::app()->user->name ?></td>
		</tr>
		<tr>
			<td>登录时间</td>
			<td><?php echo date('Y-m-d', Yii::app()->session['logintime']) ?></td>
		</tr>
		<tr>
			<td>客户端IP</td>
			<td><?php echo Yii::app()->request->userHostAddress ?></td>
		</tr>
		<tr>
			<td colspan='2' class="th"><span class="span_server" style="float:left">&nbsp</span>服务器信息</td>
		</tr>
		<tr>
			<td>服务器环境</td>
			<td><?php echo $_SERVER['SERVER_SOFTWARE'] ?></td>
		</tr>
		<tr>
			<td>PHP版本</td>
			<td><?php echo PHP_VERSION ?></td>
		</tr>
		<tr>
			<td>服务器IP</td>
			<td><?php echo $_SERVER['SERVER_ADDR'] ?></td>
		</tr>
		<tr>
			<td>数据库信息</td>
			<td><?php echo mysql_get_client_info() ?></td>
		</tr>

</table>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/modules/admin/views/default/index.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>后盾网文章系统后台管理首页</title>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/css/admin.css" />
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/admin.js"></script>
<!-- 默认打开目标 -->
<base target="iframe"/>
</head>
<body>
<!-- 头部 -->
	<div id="top_box">
		<div id="top">
			<p id="top_font">后盾网文章系统后台管理首页 （V1.1）</p>
		</div>
		<div class="top_bar">
			<p class="adm">
				<span>管理员：</span>
				<span class="adm_pic">&nbsp&nbsp&nbsp&nbsp</span>
				<span class="adm_people">[<?php echo Yii::app()->user->name ?>]</span>
			</p>
			<p class="now_time">
				今天是：2014.7.1
				您的当前位置是：
				<span>首页</span>
			</p>
			<p class="out">
				<span class="out_bg">&nbsp&nbsp&nbsp&nbsp</span>&nbsp
				<a href="<?php echo $this->createUrl('login/out') ?>" target="_self">退出</a>
			</p>
		</div>
	</div>
<!-- 左侧菜单 -->
		<div id="left_box">
			<p class="use">功能管理</p>
			<div class="menu_box">
				<h2>文章管理</h2>
				<div class="text">
				    <ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('article/add') ?>" class="pos">发表文章</a>				        	
				        </li> 
				    </ul>
					<ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('article/index') ?>" class="pos">查看文章</a>				        	
				        </li> 
				    </ul>

				</div>
			</div>	
			<div class="menu_box">
				<h2>栏目管理</h2>
				<div class="text">
					<ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('Category/index') ?>" class="pos">查看栏目</a>				        	
				        </li> 
				    </ul>
				  	<ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('Category/add') ?>" class="pos">添加栏目</a>				        	
				        </li> 
				    </ul>
				</div>
			</div>	
			<div class="menu_box">
				<h2>常用菜单</h2>
				<div class="text">
					<ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('/') ?>" class="pos" target="_blank">前台首页</a>				        	
				        </li> 
				    </ul>
				  	<ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('copy') ?>" class="pos">系统信息</a>				        	
				        </li> 
				    </ul>
				    <ul class="con">
				        <li class="nav_u">
				        	<a href="<?php echo $this->createUrl('user/passwd') ?>" class="pos">密码修改</a>				        	
				        </li> 
				    </ul>
				</div>
			</div>			
		</div>
		<!-- 右侧 -->
		<div id="right">
			<iframe  frameboder="0" border="0" 	scrolling="yes" name="iframe" src="<?php echo $this->createUrl('default/copy') ?>"></iframe>
		</div>
	<!-- 底部 -->
	<div id="foot_box">
		<div class="foot">
			<p>@Copyright © 2013-2013 houdunwang.com All Rights Reserved. 京ICP备0000000号</p>
		</div>
	</div>

</body>
</html>
<!--[if IE 6]>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/assets/admin/js/iepng.js"></script>
    <script type="text/javascript">
        DD_belatedPNG.fix('.adm_pic, #left_box .pos, .span_server, .span_people', 'background');
    </script>
<![endif]-->