Yii框架课程资料/yiiweb/blog/protected/controllers/ArticleController.php
<?php
/**
 * 文章管理控制器
 */
class ArticleController extends Controller{
	public function filters(){
		return array(
				array(
					'system.web.widgets.COutputCache + index',
					'duration'	=> 30,
					'varyByParam'=> array('aid')
					),
			);
	}
	/**
	 * 默认显示
	 */
	public function actionIndex($aid){
		$articleInfo = Article::model()->findByPk($aid);
		$this->render('index', array('articleInfo'=>$articleInfo));
	}
}

Yii框架课程资料/yiiweb/blog/protected/controllers/CategoryController.php
<?php
/**
 * 栏目管理控制器
 */
class CategoryController extends Controller{
	/**
	 * 默认显示栏目页
	 */
	public function actionIndex($cid){
		$articleInfo = Yii::app()->cache->get('cate');

		if($articleInfo == false){
			$sql = "SELECT thumb,title,info,aid FROM {{article}} WHERE cid=$cid";
			$articleInfo = Article::model()->findAllBySql($sql);
			Yii::app()->cache->set('cate',$articleInfo, 10);
		}
		


		$this->render('index', array('articleInfo'=>$articleInfo));
	}
}

Yii框架课程资料/yiiweb/blog/protected/views/layouts/blog.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>后盾网文章管理系统</title>

<link href="<?php echo Yii::app()->request->baseUrl ?>/assets/index/css/common.css" rel="stylesheet" />
</head>	
<body>
	<div id="top">
	</div>
	<div id="header">
		<div class='logo'>
			<a href=""><img src="<?php echo Yii::app()->request->baseUrl ?>/assets/index/images/logo.jpg" alt=""></a>
		</div>
		<div class='navigation'>
			<a href="<?php echo $this->createUrl("./index.html") ?>">首页</a>
			<?php 
				$artModel = Article::model();
				$common = $artModel->common();
			 ?>
			 <?php foreach($common['nav'] as $v): ?>
				<a href="<?php echo $this->createUrl('category/index', array('cid'=>$v['cid'])) ?>"><?php echo $v->cname ?></a>
			<?php endforeach ?>
		</div>
	</div>

	<?php echo $content ?>
	
	<div class='sidebar'>
			<div class='item'>
				<h2>文章标题</h2>
				<ul class='flink'>
					<?php if($this->beginCache('title', array('duration'=>5))): ?>
						<?php foreach($common['title'] as $value): ?>
							<li><a href="<?php echo $this->createUrl('article/index', array('aid'=>$value->aid)) ?>"><?php echo $value->title ?></a></li>
						<?php endforeach ?>
					<?php $this->endCache();endif; ?>
				</ul>
			</div>
			
		</div>
	</div>
	<div id="footer">
		<div class='bgbar'></div>
		<div class='bottom'>
			<div class='pos'>
				<div class='copyright'>
					© Copyright 2011-2013 www.houdunwang 后盾网
				</div>
			</div>	
		</div>
	</div>
</body>
</html>

Yii框架课程资料/yiiweb/blog/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

Yii框架课程资料/yiiweb/blog/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

Yii框架课程资料/yiiweb/blog/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>